### ISSUE TITLE
Failing Unit Tests on Windows

### ISSUE THREAD

**Issue by NeverOddOrEven** [jenkinsci/build-monitor-plugin#331]
Running com.smartcodeltd.jenkinsci.plugins.buildmonitor.BuildMonitorDescriptorTest
Tests run: 3, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.366 sec <<< FAILURE! - in com.smartcodeltd.jenkinsci.plugin.assetbundler.PathToAssetTest
combines_base_resource_url_given_by_jenkins_and_a_path_to_the_asset(com.smartcodeltd.jenkinsci.plugin.assetbundler.PathToAssetTest)  Time elapsed: 0.057 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is "/opt/jenkins/plugins/build-monitor-plugin/less/index.less"
     but: was "C:\opt\jenkins\plugins\build-monitor-plugin\less\index.less"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at com.smartcodeltd.jenkinsci.plugin.assetbundler.PathToAssetTest.combines_base_resource_url_given_by_jenkins_and_a_path_to_the_asset(PathToAssetTest.java:21)

works_with_unc_paths_on_windows(com.smartcodeltd.jenkinsci.plugin.assetbundler.PathToAssetTest)  Time elapsed: 0.012 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is "/server/jenkins/plugins/build-monitor-plugin/less/index.less"
     but: was "\\server\jenkins\plugins\build-monitor-plugin\less\index.less"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at com.smartcodeltd.jenkinsci.plugin.assetbundler.PathToAssetTest.works_with_unc_paths_on_windows(PathToAssetTest.java:30)

**Comment by NeverOddOrEven** [comment]
@jan-molak could use some input on this one. Are the assertions correct implicating a bug, or are the assertions not valid for Windows?  

I am running these tests on Windows 8.1 if that helps.

**Comment by jan-molak** [comment]
Looks like the assertions should be updated to work on Windows

**Comment by suratdas** [comment]
Fixed as part of pull request https://github.com/jan-molak/jenkins-build-monitor-plugin/pull/309
